---
- name: Install and start mongodb
  hosts: mongo_master
  remote_user: ubuntu
  become: true

  roles:
    - role: greendayonfire.mongodb
  vars:
    mongodb_net_bindip: 0.0.0.0
    mongodb_login_host: 35.166.198.238
    mongodb_security_authorization: "enabled"
    mongodb_users:
     - {
       name: user,
       password: 123456,
       roles: dbOwner,
       database: test
       }      

    # replication
    mongodb_login_host: mongo_master
    mongodb_replication_params:
      - { host_name: mongo_slave, host_port: "{{ mongodb_net_port }}", host_type: replica }

- hosts: mongo_slave
  remote_user: ubuntu
  become: true
  
  roles:
    - role: greendayonfire.mongodb
  vars:
    mongodb_net_bindip: 0.0.0.0
    mongodb_login_host: 35.166.198.238
    mongodb_security_authorization: "enabled"
    mongodb_users:
     - {
       name: testUser,
       password: passw0rd,
       roles: readWrite,
       database: test
       }

- name: Start Docker Swarm
  hosts: ['docker_engine', 'docker_swarm_manager', 'docker_swarm_worker',]
  remote_user: ubuntu
  ignore_errors: true
  become: true
  roles:
   - atosatto.docker-swarm

