

version: '2.1' 
services: 
  db-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
      - ./mongoSetup/:/docker-entrypoint-initdb.d/
    command: "--bind_ip 0.0.0.0"
  homecolis-api: 
    image: homecolis-api:latest 
    ports: 
      - "80:8080"
    links:
      - db-mongo
    depends_on:
      - db-mongo
    environment: 
      - PORT=8080
      - NODE_ENV=development
      - MONGO_HOST=db-mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=test
      - MONGO_USER=root
      - MONGO_PASSWORD=123456
volumes:
  dbdata:
  mongoSetup:
